name: Compile PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install Liberation Sans font
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-liberation
          sudo fc-cache -f -v
      - name: Compile PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -xelatex -shell-escape -8bit
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled_thesis_${{ github.sha }}
          path: main.pdf
          if-no-files-found: error
