name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full texlive-latex-extra python3-pygments

      - name: Compile Finnish PDF
        run: |
          xelatex -shell-escape -8bit main
          biber main
          makeglossaries main
          xelatex -shell-escape -8bit main
          xelatex -shell-escape -8bit main
          mkdir -p pub
          mv main.pdf pub/Pennanen_Arttu_fi.pdf

      - name: Compile English PDF (bilingual abstract)
        run: |
          sed -i 's/^\\def\\thesislang{finnish}.*/\\def\\thesislang{english}/' chapters/0info.tex
          sed -i 's/^\\def\\secondlang{english}.*/\\def\\secondlang{finnish}/' chapters/0info.tex
          xelatex -shell-escape -8bit main
          mv main.pdf pub/Pennanen_Arttu_en_bi.pdf

      - name: Compile English PDF (single abstract)
        run: |
          sed -i 's/^\\def\\bilingual{yes}.*/\\def\\bilingual{no}/' chapters/0info.tex
          xelatex -shell-escape -8bit main
          mv main.pdf pub/Pennanen_Arttu_en.pdf

      - name: Upload PDFs for download
        uses: actions/upload-artifact@v4
        with:
          name: compiled_thesis
          path: pub
