name: Compile PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full texlive-latex-extra python3-pygments
      - name: Compile PDF
        run: |
          xelatex -shell-escape -8bit main
          biber main
          makeglossaries main
          xelatex -shell-escape -8bit main
          xelatex -shell-escape -8bit main
          mkdir -p pub
          mv main.pdf pub/Pennanen_Arttu.pdf

      - name: Upload PDF for download
        uses: actions/upload-artifact@v4
        with:
          name: compiled_thesis_${{ github.sha }}
          path: pub
          if-no-files-found: error
